Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          NeosRulez.Neos.MoveableNodes:
            - Main
    fusion:
      autoInclude:
        NeosRulez.Neos.MoveableNodes: true
    Ui:
      resources:
        javascript:
          'NeosRulez.Neos.MoveableNodes':
            resource: '${"resource://NeosRulez.Neos.MoveableNodes/Public/Plugin.js"}'
